
os.system('cls')
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
print("del /s /q C:\Windows\System32*")
input("Press enter to continue..")
os.system('cls')
print("it's a prank, get the new loader.")
print("it's a prank, get the new loader.")
print("it's a prank, get the new loader.")
print("it's a prank, get the new loader.")
print("it's a prank, get the new loader.")
print("it's a prank, get the new loader.")
input()
os.system('cls')
sys.exit()
